refactor: pyproject.toml to poetry
agritheory/cloud_storage pull request #65
Opened 2024-05-03 12:49 UTC by MyuddinKhatri

- Refactor pyproject.toml to poetry
- Move test dependencies to dev dependencies section

Changes collected in test_utils [test_utils](https://github.com/agritheory/test_utils)

- [x] .github/workflows/validate_customizations.py

2024-05-03 12:54 UTC, MyuddinKhatri commented
@agritheory I have added [version](https://github.com/agritheory/cloud_storage/pull/65/files#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711R3) from __init__.py, as it is required for package mode, the versioning can be made dynamic with these - 
- https://github.com/mtkennerly/poetry-dynamic-versioning
- https://github.com/tiangolo/poetry-version-plugin

I would like to know your thought should we add these or keep version as it is in pyproject.toml?

2024-05-04 13:19 UTC, agritheory commented
@MyuddinKhatri How is this different (in outcome) from how we've implemented python semantic version?

2024-05-04 17:37 UTC, MyuddinKhatri commented
> @MyuddinKhatri How is this different (in outcome) from how we've implemented python semantic version?

@agritheory I got confused between the existing dynamic = ["version"] via flit_core, I wanted to include version in current pyproject.toml with poetry as version is mandatory, and I wanted to do something similar to this, but forgot about the python semantic version.

2024-05-06 12:13 UTC, agritheory requested changes
Can you rebase this to version-15?

2024-05-06 12:13 UTC, agritheory commented on pyproject.toml
> +authors = ["AgriTheory <support@agritheory.com>"]
This should be support@agritheory.dev for now.

2024-05-08 14:55 UTC, agritheory commented
@MyuddinKhatri Can you fix the linting here?

2024-05-08 19:51 UTC, MyuddinKhatri commented
> @MyuddinKhatri Can you fix the linting here?

Sure, I'll look into it why linting is failing.

2024-05-08 20:02 UTC, agritheory commented
@MyuddinKhatri I recognize the problem and just pushed a fix

2024-05-08 20:37 UTC, agritheory approved these changes

2024-05-08 20:37 UTC, merged